spring:
  datasource:
    # url: jdbc:postgresql://192.168.99.100:5432/tmdb?useUnicode=true&characterEncoding=utf-8
    # url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:tmdb}?useSSL=false&useUnicode=true&characterEncoding=utf-8
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:tmdb}?createDatabaseIfNotExist=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    sqlScriptEncoding: UTF-8
    initialization-mode: never
    # !!! https://auth0.com/blog/integrating-spring-data-jpa-postgresql-liquibase/
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate # do not use others wiht liqubase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
---
spring:
  profiles: dev
  datasource:
    driverClassname: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    sqlScriptEncoding: UTF-8
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2
      # http://localhost:8080/h2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect