apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-manager-database-pv
  labels:
    app: test-manager
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 0.5Gi