apiVersion: v1
kind: Service
metadata:
  name: test-manager-database
  labels:
    app: test-manager-database
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: test-manager-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-manager-database
spec:
  selector:
    matchLabels:
      app: test-manager-database
  replicas: 1
  template:
    metadata:
      labels:
        app: test-manager-database
    spec:
      containers:
        - name: postgres
          image: postgres:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: test-manager-secret
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data/pgdata"
            name: postgresql-persistent-storage
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: test-manager-database-pv

#          env:
#            - name: POSTGRES_USER
#              value: "postgres9"
#            - name: POSTGRES_PASSWORD
#              value: "postgres9"
#            - name: POSTGRES_DB
#              value: "tbooster"
# https://severalnines.com/database-blog/using-kubernetes-deploy-postgresql
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/