    CREATE SEQUENCE IF NOT EXISTS TEST_SPECIFICATION_ID_SEQ;

    CREATE TABLE TEST_SPECIFICATION (
       ID serial,
       NAME varchar(40) NOT NULL,
       STATUS varchar(20)
    );

    CREATE SEQUENCE IF NOT EXISTS TEST_RUN_ID_SEQ;

    CREATE TABLE IF NOT EXISTS test_runs (
       ID serial,
       RUN_STATUS varchar(20) NOT NULL,
       creation_time timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
       TEST_SPECIFICATION_ID INT
    );