    CREATE SEQUENCE IF NOT EXISTS TEST_SPECIFICATION_ID_SEQ;

    CREATE TABLE TEST_SPECIFICATION (
       ID serial,
       NAME varchar(40) NOT NULL,
       STATUS varchar(20)
    );

    CREATE SEQUENCE IF NOT EXISTS TEST_RUN_EXEC_STATUS_ID_SEQ;
-- TEST_RUNS TEST_RUN_STATUS or TEST_RUN_RESULTS TEST_RUN_EXEC_RESULTS
    CREATE TABLE IF NOT EXISTS TEST_RUN_EXECUTIONS_STATUS (
       ID serial,
       RUN_STATUS varchar(20) NOT NULL,
       creation_time timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
       TEST_SPECIFICATION_ID INT
    );

    CREATE TABLE IF NOT EXISTS TEST_RUNS (
           ID BIGINT,
           creation_time timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

        );